### ISSUE TITLE
PostgreSQLAdapter#sequences does not respect namespace

### ISSUE THREAD

**Issue by pascalbetz** [code42/pg_sequencer#3]
We have sequences that are in the **public** and in **bdr** namespace. All of them are listed with the query

``` ruby
sequence_names = select_all("SELECT c.relname FROM pg_class c WHERE c.relkind = 'S' order by c.relname asc").map { |row| row['relname'] }
```

(From https://github.com/code42/pg_sequencer/blob/master/lib/pg_sequencer/connection_adapters/postgresql_adapter.rb#L71)

This causes the subsequent query

``` ruby
row = select_one("SELECT * FROM #{sequence_name}")
```

to fail for the sequences that are not in **public**

IMHO the first query should be extended to include the namespace

``` ruby
sequence_names = select_all("SELECT c.relname, n.nspname FROM pg_class c inner join pg_namespace n on c.relnamespace = n.oid WHERE c.relkind = 'S' order by c.relname asc").map { |row| "#{row['nspname']}.#{row['relname']}" }
```

Feedback?

**Comment by amoravec** [comment]
Thank you for your feedback, unfortunately this project was effectively abandoned and will no longer be maintained by Code42.
